### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'length')

### ISSUE THREAD

**Issue by alcalyn** [pixijs/devtools#51]
When I have selected a container and it is highlighted, if this container is destroyed while still selected, I get this error, and the plugin seems stuck (I can change visibility, seems no longer updating).

```
Cannot read properties of null (reading 'length')
TypeError: Cannot read properties of null (reading 'length')
    at _getGlobalBounds (http://localhost:3000/statics/pixi-82aa110b902e356f211d-bundle.js:36706:43)
    at getGlobalBounds (http://localhost:3000/statics/pixi-82aa110b902e356f211d-bundle.js:36685:3)
    at Proxy.getBounds (http://localhost:3000/statics/pixi-82aa110b902e356f211d-bundle.js:37437:88)
    at Object.getGlobalBounds (chrome-extension://dlkffcaaoccbofklocbjcmppahjjboce/inject/index.js:311:14)
    at g.activateHighlight (chrome-extension://dlkffcaaoccbofklocbjcmppahjjboce/inject/index.js:197:31)
    at g.enableHighlight (chrome-extension://dlkffcaaoccbofklocbjcmppahjjboce/inject/index.js:191:89)
    at g.update (chrome-extension://dlkffcaaoccbofklocbjcmppahjjboce/inject/index.js:174:33)
    at ke.update (chrome-extension://dlkffcaaoccbofklocbjcmppahjjboce/inject/index.js:1376:52)
    at Object.apply (chrome-extension://dlkffcaaoccbofklocbjcmppahjjboce/inject/index.js:1368:18)
    at Proxy.render (http://localhost:3000/statics/pixi-82aa110b902e356f211d-bundle.js:2303:19)
```

**Comment by Zyie** [comment]
Hey, thanks for reporting this, will look into it today

**Comment by Zyie** [comment]
This should be fixed in the latest version so closing for now!
